### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by Dierney**
Well well well, I know it's very small. But it's important, isn't it?

### CODE REVIEW

**Comment by Antirhinnum** [comment]
Thanks for adding the translation! I agree, it's fairly important, given not everyone speaks English. Again, thank you!

**Comment by Dierney** [comment]
It's nothing. Yep, not everyone speaks English. Say you are not afraid of jokes, in our Chinese community, it’s really very, very many Terrarian can’t speak English. Therefore, some of us have established 抗药又坚硬汉化组(SBMW) to add Chinese translations for mods.

**Comment by Antirhinnum** [comment]
Ah. Well, good luck!

**Comment by Dierney** [comment]
Good luck too! Hope your mod to get better and better, keep! (：

**Pull request merged**
